# Group Activity, Week 14, Heather Leighton-Dick

## 1. Using the documentation for Recursive Feature Selection, apply this process to the crime dataset to create the best multivariate linear regression model https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html . You can select what you’re trying to predict, but be sure to indicate what that is. Be sure to explain what RFE is in the markdown. You should be able to answer this using what’s on the documentation page + what you already know.


### Recursive feature elimination (RFE) is the process of programmatically narrowing down the features of a dataset based on the relative importance of each feature. The features are ranked in an array with the first ranking (of 1) given to the selected best feature(s).

### The feature assigned a "1" in the array below is the selected "best" feature ('X4'). X4 is the percentage of people aged 25 years or older with 4 years of high school education, so the model seems to be positing that the most relevant feature correlated to the crime rate is high school education.

In [7]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostRegressor

crime_df = pd.read_csv("crime_data.csv")
crime_df.head()

X1   X2  X3  X4  X5  X6  X7
0  478  184  40  74  11  31  20
1  494  213  32  72  11  43  18
2  643  347  57  70  18  16  16
3  341  565  31  71  11  25  19
4  773  327  67  72   9  29  24

In [9]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

#dataset variables
X = crime_df.drop('X1', axis=1)
y = crime_df['X1']

estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=1, step=1)
selector = selector.fit(X, y)

selector.support_
#array([ True,  True,  True,  True,  True, False, False, False, False,
#       False])

selector.ranking_
#array([1, 1, 1, 1, 1, 6, 4, 3, 2, 5])



array([6, 2, 3, 1, 4, 5])

## 2. Create a list of preprocessing steps you should try when working to build a model. Briefly describe what each step is. Work with your group to come up with the most comprehensive list you can.

-- NaN values: .isnull().sum()
-- filling NaNs with mean, mode, most-frequent strategies
-- look for alternate values and replace if need be - ?, 0's

-- .dtypes - checking for timestamps, string objects, numbers stored as numbers not categories

-- renaming columns to be standardized and clearly labelled

-- look for duplicate/redundant columns/values

-- StandardScaler - scaling the data
-- plot data - skewed data? this will help with knowing what preprocessing to do

-- One Hot Encoding for categorical values
-- correlation matrices to see where there is multicollinearity